#
# See https://docs.boltic.io/docs/compute/serverless/application-config for information about how to use this file.
#

app = "golang-buildpack-app-sample"
region = "asia-south1"
entrpoint = "main.go"

[build]
  buildpack_builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = ["paketo-buildpacks/go"]
  ignorefile = ".gitignore"
  [build.args]
    foo = "bar"

[env]
  FOO = "BAR"
